import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";
import { ThemeConfig } from "flowbite-react";
import ToasterProvider from "./providers/ToasterProvider";

export const metadata: Metadata = {
  title: "Microservices",
  description: "Generated by Microservices",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ThemeConfig dark={false} />
      <html lang="en">
        <body>
          <ToasterProvider />
          <Navbar />
          <main className="container mx-auto px-5 pt-10">{children}</main>
        </body>
      </html>
    </>
  );
}
